### ISSUE TITLE
Consider releasing some of graphics?

### ISSUE THREAD

**Issue by ScatteredRay** [keengames/vulkan_backend#1]
Trying to review this code to get a sense of its architecture there is a lot. Missing to understand how it fits into the bigger picture. 

I think at least also releasing `keen/graphics/graphics_types.hpp` and it’s structures would be very helpful.

**Comment by jkoenen** [comment]
In commit 7f9e56597677706c2f00228287cd8bde5f1c0be7 I included the graphics_types.hpp header - I hope that clears some things up.
